// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nwakkzwqyfhbuzpzmals.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53YWtrendxeWZoYnV6cHptYWxzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMTcxMDMsImV4cCI6MjA2MzU5MzEwM30.eIFXmSlyrdh6MRsnvyeEsXDQU312PLpGx9xZBqruK_M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);